import { Database } from "bun:sqlite";
import { writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { $ } from "bun";
import { bedrockEmbedImage } from "../lib/rag-image-embed";
import { QUERY_PURPOSE } from "../lib/rag-models";
import { normalizeRawgMediaPath, RAWG_MEDIA_PREFIX } from "../lib/rawg-image-path";

const DEFAULT_DB = "/home/siskandar/Downloads/p/videogames_with_embeddings.db";
const K = 10;

const { values } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    db: { type: "string", default: DEFAULT_DB },
    sample: { type: "string", default: "50" },
    stride: { type: "string", default: "421" },
    out: { type: "string", default: "evaluation/06-cross-modal.md" },
    purpose: { type: "string" },
  },
});
const purpose = values.purpose ?? QUERY_PURPOSE;

type Row = { id: number; name: string; background_image: string | null };
type Hit = { rawgId: number; score: number; modality: string };

const db = new Database(values.db ?? DEFAULT_DB, { readonly: true });
const all = db.query("SELECT id, name, background_image FROM games ORDER BY id").all() as Row[];
const stride = Number.parseInt(values.stride ?? "421", 10);
const sampleSize = Number.parseInt(values.sample ?? "50", 10);
const sample: Row[] = [];
for (let index = 0; index < all.length && sample.length < sampleSize; index += stride) {
  const row = all[index];
  if (row?.background_image) sample.push(row);
}

let imageAt1 = 0;
let imageAt10 = 0;
let textAt10 = 0;
let anyAt10 = 0;
let evaluated = 0;
const searchTimes: number[] = [];
const rows: string[] = [];

for (const row of sample) {
  const path = normalizeRawgMediaPath(row.background_image ?? "");
  if (path === null) continue;
  const response = await fetch(`${RAWG_MEDIA_PREFIX}resize/640/-/${path}`);
  if (!response.ok) continue;
  const bytes = new Uint8Array(await response.arrayBuffer());
  const { embedding } = await bedrockEmbedImage(bytes, purpose);
  const raw =
    await $`bunx convex run rag:debugSearchVector ${JSON.stringify({ vector: embedding, limit: K * 2 })}`
      .quiet()
      .text();
  const result = JSON.parse(raw.slice(raw.indexOf("{"))) as { searchMs: number; hits: Hit[] };
  searchTimes.push(result.searchMs);
  evaluated += 1;
  const imageHits = result.hits.filter((hit) => hit.modality === "image").slice(0, K);
  const textHits = result.hits.filter((hit) => hit.modality === "text").slice(0, K);
  const imageRank = imageHits.findIndex((hit) => hit.rawgId === row.id);
  const textRank = textHits.findIndex((hit) => hit.rawgId === row.id);
  if (imageRank === 0) imageAt1 += 1;
  if (imageRank >= 0) imageAt10 += 1;
  if (textRank >= 0) textAt10 += 1;
  if (imageRank >= 0 || textRank >= 0) anyAt10 += 1;
  rows.push(
    `| ${row.name} | ${imageRank >= 0 ? `rank ${imageRank + 1}` : "miss"} | ${textRank >= 0 ? `rank ${textRank + 1}` : "miss"} | ${(imageHits[0]?.score ?? 0).toFixed(3)} |`
  );
  console.log(
    `${row.name}: image=${imageRank >= 0 ? imageRank + 1 : "miss"} text=${textRank >= 0 ? textRank + 1 : "miss"}`
  );
}

const sorted = [...searchTimes].sort((a, b) => a - b);
const p = (q: number) => sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))] ?? 0;
const pct = (n: number) => `${((100 * n) / Math.max(evaluated, 1)).toFixed(1)}%`;
writeFileSync(
  values.out ?? "",
  `# Cross-modal retrieval: cover art as the query

Generated by \`bun run scripts/rag-crossmodal.ts\` on ${new Date().toISOString().slice(0, 10)}. ${evaluated} corpus games sampled at a fixed stride; each game's own 640px cover is embedded with Nova as a query (\`${purpose}\`) and searched twice against the shared index: once filtered to the cover-art vectors (modality \`image\`) and once to the text-document vectors (modality \`text\`), top ${K} each.

| Measure | Value |
| --- | --- |
| Cover finds its own cover-art vector at rank 1 (image to image) | ${imageAt1} / ${evaluated} = ${pct(imageAt1)} |
| Cover finds its own cover-art vector in the top ${K} | ${imageAt10} / ${evaluated} = ${pct(imageAt10)} |
| Cover finds the game's text document in the top ${K} (image to text, the genuinely cross-modal case) | ${textAt10} / ${evaluated} = ${pct(textAt10)} |
| Either modality in the top ${K} | ${anyAt10} / ${evaluated} = ${pct(anyAt10)} |
| Vector search latency p50 / p95 (44,850 vectors, modality filter) | ${p(0.5)}ms / ${p(0.95)}ms |

| Game | Image rank | Text rank | Top image score |
| --- | --- | --- | --- |
${rows.join("\n")}
`
);
console.log(
  `image@1=${imageAt1} image@10=${imageAt10} text@10=${textAt10} any@10=${anyAt10} of ${evaluated}`
);
