import { Database } from "bun:sqlite";
import { readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { $ } from "bun";

const DEFAULT_DB = "/home/siskandar/Downloads/p/videogames_with_embeddings.db";
const K = 10;

const { values } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    db: { type: "string", default: DEFAULT_DB },
    pairs: { type: "string", default: "evaluation/similar-pairs.json" },
    out: { type: "string", default: "evaluation/04-recall-at-10.md" },
  },
});

type CorpusRow = {
  id: number;
  slug: string;
  name: string;
  genres: string | null;
  rating: number | null;
  metacritic: number | null;
};

const db = new Database(values.db ?? DEFAULT_DB, { readonly: true });
const all = db
  .query("SELECT id, slug, name, genres, rating, metacritic FROM games")
  .all() as CorpusRow[];
const bySlug = new Map(all.map((row) => [row.slug, row]));
const byId = new Map(all.map((row) => [row.id, row]));
const genresOf = (row: CorpusRow): Set<string> =>
  new Set(
    (row.genres ?? "")
      .split(",")
      .map((g) => g.trim())
      .filter((g) => g.length > 0)
  );

function genreBaseline(seed: CorpusRow): number[] {
  const seedGenres = genresOf(seed);
  const scored: Array<{ id: number; jaccard: number; rating: number }> = [];
  for (const row of all) {
    if (row.id === seed.id) continue;
    const g = genresOf(row);
    let shared = 0;
    for (const genre of g) if (seedGenres.has(genre)) shared += 1;
    if (shared === 0) continue;
    const union = new Set([...g, ...seedGenres]).size;
    scored.push({ id: row.id, jaccard: shared / union, rating: row.rating ?? 0 });
  }
  scored.sort((a, b) => b.jaccard - a.jaccard || b.rating - a.rating);
  return scored.slice(0, K).map((entry) => entry.id);
}

const pairs = JSON.parse(readFileSync(values.pairs ?? "", "utf8")) as Array<[string, string]>;
let ragHits = 0;
let baselineHits = 0;
let evaluated = 0;
const searchTimes: number[] = [];
const rows: string[] = [];

for (const [seedSlug, targetSlug] of pairs) {
  const seed = bySlug.get(seedSlug);
  const target = bySlug.get(targetSlug);
  if (seed === undefined || target === undefined) {
    rows.push(`| ${seedSlug} | ${targetSlug} | skipped (not in corpus) | |`);
    continue;
  }
  evaluated += 1;
  const raw =
    await $`bunx convex run rag:debugSimilar ${JSON.stringify({ rawgId: seed.id, limit: K })}`
      .quiet()
      .text();
  const result = JSON.parse(raw.slice(raw.indexOf("{"))) as {
    searchMs: number;
    hits: Array<{ rawgId: number; score: number }>;
  };
  searchTimes.push(result.searchMs);
  const ragRank = result.hits.findIndex((hit) => hit.rawgId === target.id);
  const baseRank = genreBaseline(seed).indexOf(target.id);
  if (ragRank >= 0) ragHits += 1;
  if (baseRank >= 0) baselineHits += 1;
  const top3 = result.hits
    .slice(0, 3)
    .map((hit) => byId.get(hit.rawgId)?.name ?? hit.rawgId)
    .join(", ");
  rows.push(
    `| ${seed.name} | ${target.name} | ${ragRank >= 0 ? `rank ${ragRank + 1}` : "miss"} | ${baseRank >= 0 ? `rank ${baseRank + 1}` : "miss"} | ${top3} |`
  );
  console.log(
    `${seed.name} -> ${target.name}: rag=${ragRank >= 0 ? ragRank + 1 : "miss"} genre=${baseRank >= 0 ? baseRank + 1 : "miss"}`
  );
}

const sorted = [...searchTimes].sort((a, b) => a - b);
const p = (q: number) => sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))] ?? 0;
const md = `# Recall@${K} over ${evaluated} hand-labelled similar-game pairs

Generated by \`bun run scripts/rag-recall.ts\` on ${new Date().toISOString().slice(0, 10)}. For each (seed, target) pair, the seed's own stored vector is the query and the pair counts as a hit if the target is in the top ${K} neighbours. The genre baseline ranks the corpus by Jaccard overlap of RAWG genre sets with the seed, ties broken by RAWG rating, which is what a "sort by genre" list would give.

| Method | Recall@${K} |
| --- | --- |
| Vector search (Nova 1024-dim, GENERIC_INDEX on both sides since the seed is a stored document) | **${ragHits} / ${evaluated} = ${((100 * ragHits) / Math.max(evaluated, 1)).toFixed(1)}%** |
| Genre-list baseline | ${baselineHits} / ${evaluated} = ${((100 * baselineHits) / Math.max(evaluated, 1)).toFixed(1)}% |

Vector search latency (Convex \`ctx.vectorSearch\`, 21k vectors): p50 ${p(0.5)}ms, p95 ${p(0.95)}ms.

| Seed | Target | Vector rank | Genre rank | Vector top 3 |
| --- | --- | --- | --- | --- |
${rows.join("\n")}
`;
writeFileSync(values.out ?? "", md);
console.log(`\nrecall@${K}: rag=${ragHits}/${evaluated} genre=${baselineHits}/${evaluated}`);
